- title: "EnvironmentalEffects"
  children:
    - title: "Background"
      url: /components/environmentaleffects/background/
    - title: "Fog"
      url: /components/environmentaleffects/fog/
    - title: "FogCoordinate"
      url: /components/environmentaleffects/fogcoordinate/
    - title: "LocalFog"
      url: /components/environmentaleffects/localfog/
    - title: "TextureBackground"
      url: /components/environmentaleffects/texturebackground/
