<<<<<<< HEAD
# theme settings
remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "dark" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise", "default"

# Site Settings
locale: "en-US"
title: "X_ITE X3D Browser"
title_separator: "-"
subtitle: "Postdoctoral scholar"
name: "Holger Seelig"
description: "Holger Seelig"
words_per_minute: 200
github: [metadata]

# Build settings
=======
theme: jekyll-theme-architect
>>>>>>> ddf8a91c638ee5831a2e3cd2da453e574c2235b7
plugins:
  - jekyll-relative-links

relative_links:
  enabled: true
  collections: true
include:
  - Home.md

## defaults
defaults:
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      classes: wide
      author_profile: false
      sidebar:
        nav: pages  # _posts
