#theme: jekyll-theme-cayman
remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "dark" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise", "default"

# Site Settings
locale: "en-US"
title: &title "X_ITE X3D Browser"
title_separator: "-"
subtitle: "One Step Ahead"
name: &name "Holger Seelig"
description: *name
words_per_minute: 200
github: [metadata]

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache
  - jekyll-titles-from-headings
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-relative-links

# Site Author
author:
  name: *title
  avatar: "logo.png"
  bio: "Version 4.0.1"
  links:
    - label: "GitHub"
      icon: "fab fa-2x fa-fw fa-github"
      url: "https://github.com/create3000/x_ite"

footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github-square"
      url: "https://github.com/create3000/x_ite"

relative_links:
  enabled: true
  collections: true

titles_from_headings:
  enabled: false
  strip_title: true
  collections: true

include:
  - index.md
  - What's-New.md

# markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# # Conversion
encoding: "utf-8"
markdown: GFM
# markdown: kramdown
# highlighter: rouge
# lsi: false
# excerpt_separator: "\n\n"
# incremental: false

# # Markdown Processing
# kramdown:
#   input: GFM
#   hard_wrap: false
#   auto_ids: true
#   footnote_nr: 1
#   entity_output: as_char
#   toc_levels: 1..6
#   smart_quotes: lsquo,rsquo,ldquo,rdquo
#   enable_coderay: false

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed # https://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style

# documentation links
pages:
  - title: "Quick-Start Guide"
    children:
      - title: "Getting Started"
        url: /
      - title: "What's New"
        url: /What's-New.html
  - title: Customization
    children:
      - title: "Configuration"
        url: /docs/configuration/
      - title: "Overriding Theme Defaults"
        url: /docs/overriding-theme-defaults/
      - title: "Navigation"
        url: /docs/navigation/
      - title: "UI Text"
        url: /docs/ui-text/
      - title: "Authors"
        url: /docs/authors/
      - title: "Layouts"
        url: /docs/layouts/

## defaults
defaults:
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      classes: wide
      author_profile: true
      sidebar:
        nav: "pages"
