# theme settings
#remote_theme: "mmistakes/minimal-mistakes"
#minimal_mistakes_skin: "dark" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise", "default"

# Build settings
plugins:
  - jekyll-remote-theme
  - jekyll-relative-links

relative_links:
  enabled: true
  collections: true
include:
  - Home.md

## defaults
defaults:
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      classes: wide
      author_profile: false
      sidebar:
        nav: pages # _posts

theme: jekyll-theme-cayman
