#theme: jekyll-theme-cayman
remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "dark" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise", "default"

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache
  - jekyll-titles-from-headings
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - Home.md
