
#Theme docs
#https://github.com/mmistakes/minimal-mistakes
#https://github.com/mluerig/personal-homepage

remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "air" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise", "default"

# Site Settings
locale: "en-US"
title: &title "X_ITE X3D Browser"
title_separator: "-"
subtitle: "One Step Ahead"
name: &name "Holger Seelig"
description: *name
words_per_minute: 200
github: [metadata]

# Search
search: true
search_full_content: true
search_provider: google
google:
  search_engine_id: 36920ccf3f21ca6d5

# Site Author
author:
  name: *title
  avatar: "logo.png"
  bio: "Version 4.7.0"
  links:
    - label: "GitHub"
      icon: "fab fa-2x fa-fw fa-github"
      url: "https://github.com/create3000/x_ite"

footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github-square"
      url: "https://github.com/create3000/x_ite"

titles_from_headings:
  enabled: false
  strip_title: true
  collections: true

relative_links:
  enabled: true
  collections: true

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache
  - jekyll-titles-from-headings
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-relative-links

# markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# # Conversion
encoding: "utf-8"
markdown: GFM
# markdown: kramdown
# highlighter: rouge
# lsi: false
# excerpt_separator: "\n\n"
# incremental: false

# # Markdown Processing
# kramdown:
#   input: GFM
#   hard_wrap: false
#   auto_ids: true
#   footnote_nr: 1
#   entity_output: as_char
#   toc_levels: 1..6
#   smart_quotes: lsquo,rsquo,ldquo,rdquo
#   enable_coderay: false

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed # https://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style

## defaults
defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      classes: wide
      author_profile: true
      sidebar:
        nav: pages

include:
  - Accessing-the-External-Browser.md
  - Adding-backgrounds.md
  - Adding-fog.md
  - Adding-sound.md
  - Animating-transforms.md
  - Basic-Nodes.md
  - Browser-Services.md
  - Browser-Support.md
  - Building-a-X3D-world.md
  - Building-elevation-grids.md
  - Building-extruded-shapes.md
  - Building-primitive-shapes.md
  - Building-shapes-out-of-points,-lines,-and-faces.md
  - Constants-Service.md
  - Controlling-appearance-with-materials.md
  - Controlling-color-on-coordinate-based-geometry.md
  - Controlling-detail.md
  - Controlling-how-textures-are-mapped.md
  - Controlling-navigation.md
  - Controlling-shading-on-coordinate-based-geometry.md
  - Controlling-the-viewpoint.md
  - Creating-new-node-types.md
  - Custom-Shaders.md
  - ECMAScript-Object-and-Function-Definitions.md
  - Features.md
  - Field-Services-and-Objects.md
  - Glossary.md
  - Grouping-nodes.md
  - Hello,-World!.md
  - How-To-Configure-Your-Web-Server.md
  - Improving-Performance.md
  - Increasing-Rendering-Speed.md
  - Introducing-X3D.md
  - Introducing-animation.md
  - Introducing-script-use.md
  - Lighting-your-world.md
  - Mapping-textures.md
  - Naming-nodes.md
  - Prototype-Services.md
  - Providing-information-about-your-world.md
  - Route-services.md
  - Scene-Services.md
  - Script-Node-Authoring-Interface.md
  - Sensing-the-viewer.md
  - Sensing-viewer-actions.md
  - Supported-Nodes.md
  - Transforming-Shapes.md
  - Tutorials.md
  - What's-New.md
  - Writing-program-scripts-with-ECMAScript.md
  - XHTML-DOM-Integration.md
  - index.md
