
#Theme docs
#https://github.com/mmistakes/minimal-mistakes
#https://github.com/mluerig/personal-homepage

remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "air" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise", "default"

# Site Settings
locale: "en-US"
title: &title "X_ITE X3D Browser"
title_separator: "-"
subtitle: "Shaping the Future of Space and Time"
name: &name "Holger Seelig"
description: *name
words_per_minute: 200
github: [metadata]

# Site Author
author:
  name: *title
  avatar: "assets/images/logo.png"
  bio: "Version 4.7.14"
  links:
    - label: "GitHub"
      icon: "fab fa-2x fa-fw fa-github"
      url: "https://github.com/create3000/x_ite"

footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github-square"
      url: "https://github.com/create3000/x_ite"
    - label: "D3 X3D"
      icon: "fas fa-fw fa-link"
      url: "https://github.com/jamesleesaunders/d3-x3d"
    - label: "Titania X3D Editor"
      icon: "fas fa-fw fa-link"
      url: "https://github.com/create3000/titania/wiki"
    - label: "Web3D.org"
      icon: "fas fa-fw fa-link"
      url: "https://www.web3d.org"

# Search
search: true
search_full_content: true
search_provider: google
google:
  search_engine_id: 36920ccf3f21ca6d5

titles_from_headings:
  enabled: false
  strip_title: true
  collections: true

relative_links:
  enabled: true
  collections: true

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-last-modified-at
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache
  - jekyll-titles-from-headings
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-relative-links

# Conversion
encoding: "utf-8"
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed # https://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style

# Defaults
defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      classes: wide
      author_profile: true
      sidebar:
        nav: pages
  - scope:
      path: "reference"
      type: pages
    values:
      layout: single
      classes: wide
      author_profile: true
      sidebar:
        nav: reference
  - scope:
      path: "tutorials"
      type: pages
    values:
      layout: single
      classes: wide
      author_profile: true
      sidebar:
        nav: tutorials

# Fiels and folders
include:
  - 404.md
  - Accessing-the-External-Browser.md
  - Browser-Support.md
  - Custom-Shaders.md
  - Features.md
  - Glossary.md
  - How-To-Configure-Your-Web-Server.md
  - Supported-Nodes.md
  - What's-New.md
  - XHTML-DOM-Integration.md
  - index.md
  - reference
  - tutorials
